/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WatchMovieIdRouteImport } from './routes/watch.$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMovieIdRoute = WatchMovieIdRouteImport.update({
  id: '/watch/$movieId',
  path: '/watch/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/profile': typeof ProfileRoute
  '/watch/$movieId': typeof WatchMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/profile': typeof ProfileRoute
  '/watch/$movieId': typeof WatchMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/profile': typeof ProfileRoute
  '/watch/$movieId': typeof WatchMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-list' | '/profile' | '/watch/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-list' | '/profile' | '/watch/$movieId'
  id: '__root__' | '/' | '/my-list' | '/profile' | '/watch/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyListRoute: typeof MyListRoute
  ProfileRoute: typeof ProfileRoute
  WatchMovieIdRoute: typeof WatchMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$movieId': {
      id: '/watch/$movieId'
      path: '/watch/$movieId'
      fullPath: '/watch/$movieId'
      preLoaderRoute: typeof WatchMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyListRoute: MyListRoute,
  ProfileRoute: ProfileRoute,
  WatchMovieIdRoute: WatchMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
